/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Sun May 28 08:33:58 CEST 2023
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif

// Core Global Definitions
char Shared[553]; //  size:= 553*char
char *const FIFO_Head_B_0_end_back__B_1_init_feed__0 = (char*) (Shared + 264); // FIFO_Head_B_0_end_back > B_1_init_feed size:= 1*char
char *const frk_init_in__frk_0__0 = (char*) (Shared + 0);  // frk_init_in > frk_0 size:= 60*char
char *const implode_A_end_outA_outA__A_end_outA__0 = (char*) (Shared + 0); // implode_A_end_outA_outA > A_end_outA size:= 60*char
char *const A_0__implode_A_end_outA_outA__0 = (char*) (Shared + 64);  // A_0 > implode_A_end_outA_outA size:= 20*char
char *const A_1__implode_A_end_outA_outA__0 = (char*) (Shared + 88);  // A_1 > implode_A_end_outA_outA size:= 20*char
char *const A_2__implode_A_end_outA_outA__0 = (char*) (Shared + 112);  // A_2 > implode_A_end_outA_outA size:= 20*char
char *const jn_0__snk_0__0 = (char*) (Shared + 64);  // jn_0 > snk_0 size:= 17*char
char *const B_1_init_feed__B_1_0__0 = (char*) (Shared + 136);  // B_1_init_feed > B_1_0 size:= 1*char
char *const B_2_init_feed__B_2_0__0 = (char*) (Shared + 144);  // B_2_init_feed > B_2_0 size:= 1*char
char *const B_3_init_feed__B_3_0__0 = (char*) (Shared + 152);  // B_3_init_feed > B_3_0 size:= 1*char
char *const B_4_init_feed__B_4_0__0 = (char*) (Shared + 160);  // B_4_init_feed > B_4_0 size:= 1*char
char *const B_5_init_feed__B_5_0__0 = (char*) (Shared + 168);  // B_5_init_feed > B_5_0 size:= 1*char
char *const B_6_init_feed__B_6_0__0 = (char*) (Shared + 176);  // B_6_init_feed > B_6_0 size:= 1*char
char *const B_7_init_feed__B_7_0__0 = (char*) (Shared + 184);  // B_7_init_feed > B_7_0 size:= 1*char
char *const B_8_init_feed__B_8_0__0 = (char*) (Shared + 192);  // B_8_init_feed > B_8_0 size:= 1*char
char *const B_9_init_feed__B_9_0__0 = (char*) (Shared + 200);  // B_9_init_feed > B_9_0 size:= 1*char
char *const B_10_init_feed__B_10_0__0 = (char*) (Shared + 208);  // B_10_init_feed > B_10_0 size:= 1*char
char *const B_11_init_feed__B_11_0__0 = (char*) (Shared + 216);  // B_11_init_feed > B_11_0 size:= 1*char
char *const B_12_init_feed__B_12_0__0 = (char*) (Shared + 224);  // B_12_init_feed > B_12_0 size:= 1*char
char *const B_13_init_feed__B_13_0__0 = (char*) (Shared + 232);  // B_13_init_feed > B_13_0 size:= 1*char
char *const B_14_init_feed__B_14_0__0 = (char*) (Shared + 240);  // B_14_init_feed > B_14_0 size:= 1*char
char *const B_15_init_feed__B_15_0__0 = (char*) (Shared + 248);  // B_15_init_feed > B_15_0 size:= 1*char
char *const B_16_init_feed__B_16_0__0 = (char*) (Shared + 256);  // B_16_init_feed > B_16_0 size:= 1*char
char *const set_0__B_0_0__0 = (char*) (Shared + 264);  // set_0 > B_0_0 size:= 1*char
char *const frk_0__B_0_0__0 = (char*) (Shared + 272);  // frk_0 > B_0_0 size:= 1*char
char *const frk_0__B_1_0__0 = (char*) (Shared + 280);  // frk_0 > B_1_0 size:= 1*char
char *const frk_0__B_2_0__0 = (char*) (Shared + 288);  // frk_0 > B_2_0 size:= 1*char
char *const frk_0__B_3_0__0 = (char*) (Shared + 296);  // frk_0 > B_3_0 size:= 1*char
char *const frk_0__B_4_0__0 = (char*) (Shared + 304);  // frk_0 > B_4_0 size:= 1*char
char *const frk_0__B_5_0__0 = (char*) (Shared + 312);  // frk_0 > B_5_0 size:= 1*char
char *const frk_0__B_6_0__0 = (char*) (Shared + 320);  // frk_0 > B_6_0 size:= 1*char
char *const frk_0__B_7_0__0 = (char*) (Shared + 328);  // frk_0 > B_7_0 size:= 1*char
char *const frk_0__B_8_0__0 = (char*) (Shared + 336);  // frk_0 > B_8_0 size:= 1*char
char *const frk_0__B_9_0__0 = (char*) (Shared + 344);  // frk_0 > B_9_0 size:= 1*char
char *const frk_0__B_10_0__0 = (char*) (Shared + 352);  // frk_0 > B_10_0 size:= 1*char
char *const frk_0__B_11_0__0 = (char*) (Shared + 360);  // frk_0 > B_11_0 size:= 1*char
char *const frk_0__B_12_0__0 = (char*) (Shared + 368);  // frk_0 > B_12_0 size:= 1*char
char *const frk_0__B_13_0__0 = (char*) (Shared + 376);  // frk_0 > B_13_0 size:= 1*char
char *const frk_0__B_14_0__0 = (char*) (Shared + 384);  // frk_0 > B_14_0 size:= 1*char
char *const frk_0__B_15_0__0 = (char*) (Shared + 392);  // frk_0 > B_15_0 size:= 1*char
char *const frk_0__B_16_0__0 = (char*) (Shared + 400);  // frk_0 > B_16_0 size:= 1*char
char *const B_5_0__B_5_end_back__0 = (char*) (Shared + 136);  // B_5_0 > B_5_end_back size:= 1*char
char *const B_5_0__jn_0__0 = (char*) (Shared + 208);  // B_5_0 > jn_0 size:= 1*char
char *const B_1_0__B_1_end_back__0 = (char*) (Shared + 232);  // B_1_0 > B_1_end_back size:= 1*char
char *const B_1_0__jn_0__0 = (char*) (Shared + 352);  // B_1_0 > jn_0 size:= 1*char
char *const B_9_0__B_9_end_back__0 = (char*) (Shared + 168);  // B_9_0 > B_9_end_back size:= 1*char
char *const B_9_0__jn_0__0 = (char*) (Shared + 280);  // B_9_0 > jn_0 size:= 1*char
char *const B_10_0__B_10_end_back__0 = (char*) (Shared + 408);  // B_10_0 > B_10_end_back size:= 1*char
char *const B_10_0__jn_0__0 = (char*) (Shared + 416);  // B_10_0 > jn_0 size:= 1*char
char *const B_13_0__B_13_end_back__0 = (char*) (Shared + 424);  // B_13_0 > B_13_end_back size:= 1*char
char *const B_13_0__jn_0__0 = (char*) (Shared + 432);  // B_13_0 > jn_0 size:= 1*char
char *const B_0_0__B_0_end_back__0 = (char*) (Shared + 160);  // B_0_0 > B_0_end_back size:= 1*char
char *const B_0_0__jn_0__0 = (char*) (Shared + 192);  // B_0_0 > jn_0 size:= 1*char
char *const B_2_0__B_2_end_back__0 = (char*) (Shared + 216);  // B_2_0 > B_2_end_back size:= 1*char
char *const B_2_0__jn_0__0 = (char*) (Shared + 240);  // B_2_0 > jn_0 size:= 1*char
char *const B_3_0__B_3_end_back__0 = (char*) (Shared + 224);  // B_3_0 > B_3_end_back size:= 1*char
char *const B_3_0__jn_0__0 = (char*) (Shared + 248);  // B_3_0 > jn_0 size:= 1*char
char *const B_4_0__B_4_end_back__0 = (char*) (Shared + 256);  // B_4_0 > B_4_end_back size:= 1*char
char *const B_4_0__jn_0__0 = (char*) (Shared + 400);  // B_4_0 > jn_0 size:= 1*char
char *const B_6_0__B_6_end_back__0 = (char*) (Shared + 144);  // B_6_0 > B_6_end_back size:= 1*char
char *const B_6_0__jn_0__0 = (char*) (Shared + 288);  // B_6_0 > jn_0 size:= 1*char
char *const B_7_0__B_7_end_back__0 = (char*) (Shared + 152);  // B_7_0 > B_7_end_back size:= 1*char
char *const B_7_0__jn_0__0 = (char*) (Shared + 296);  // B_7_0 > jn_0 size:= 1*char
char *const B_8_0__B_8_end_back__0 = (char*) (Shared + 304);  // B_8_0 > B_8_end_back size:= 1*char
char *const B_8_0__jn_0__0 = (char*) (Shared + 440);  // B_8_0 > jn_0 size:= 1*char
char *const B_11_0__B_11_end_back__0 = (char*) (Shared + 448);  // B_11_0 > B_11_end_back size:= 1*char
char *const B_11_0__jn_0__0 = (char*) (Shared + 456);  // B_11_0 > jn_0 size:= 1*char
char *const B_12_0__B_12_end_back__0 = (char*) (Shared + 464);  // B_12_0 > B_12_end_back size:= 1*char
char *const B_12_0__jn_0__0 = (char*) (Shared + 472);  // B_12_0 > jn_0 size:= 1*char
char *const B_14_0__B_14_end_back__0 = (char*) (Shared + 360);  // B_14_0 > B_14_end_back size:= 1*char
char *const B_14_0__jn_0__0 = (char*) (Shared + 480);  // B_14_0 > jn_0 size:= 1*char
char *const B_15_0__B_15_end_back__0 = (char*) (Shared + 368);  // B_15_0 > B_15_end_back size:= 1*char
char *const B_15_0__jn_0__0 = (char*) (Shared + 488);  // B_15_0 > jn_0 size:= 1*char
char *const B_16_0__jn_0__0 = (char*) (Shared + 496);  // B_16_0 > jn_0 size:= 1*char
char *const B_16_0__snk2_0__0 = (char*) (Shared + 504);  // B_16_0 > snk2_0 size:= 1*char
char *const FIFO_Head_A_end_outA__frk_init_in__0 = (char*) (Shared + 0); // FIFO_Head_A_end_outA > frk_init_in size:= 60*char
char *const FIFO_Head_B_1_end_back__B_2_init_feed__0 = (char*) (Shared + 312); // FIFO_Head_B_1_end_back > B_2_init_feed size:= 1*char
char *const FIFO_Head_B_2_end_back__B_3_init_feed__0 = (char*) (Shared + 176); // FIFO_Head_B_2_end_back > B_3_init_feed size:= 1*char
char *const FIFO_Head_B_3_end_back__B_4_init_feed__0 = (char*) (Shared + 184); // FIFO_Head_B_3_end_back > B_4_init_feed size:= 1*char
char *const FIFO_Head_B_4_end_back__B_5_init_feed__0 = (char*) (Shared + 320); // FIFO_Head_B_4_end_back > B_5_init_feed size:= 1*char
char *const FIFO_Head_B_5_end_back__B_6_init_feed__0 = (char*) (Shared + 448); // FIFO_Head_B_5_end_back > B_6_init_feed size:= 1*char
char *const FIFO_Head_B_6_end_back__B_7_init_feed__0 = (char*) (Shared + 464); // FIFO_Head_B_6_end_back > B_7_init_feed size:= 1*char
char *const FIFO_Head_B_7_end_back__B_8_init_feed__0 = (char*) (Shared + 328); // FIFO_Head_B_7_end_back > B_8_init_feed size:= 1*char
char *const FIFO_Head_B_8_end_back__B_9_init_feed__0 = (char*) (Shared + 512); // FIFO_Head_B_8_end_back > B_9_init_feed size:= 1*char
char *const FIFO_Head_B_9_end_back__B_10_init_feed__0 = (char*) (Shared + 200); // FIFO_Head_B_9_end_back > B_10_init_feed size:= 1*char
char *const FIFO_Head_B_10_end_back__B_11_init_feed__0 = (char*) (Shared + 520); // FIFO_Head_B_10_end_back > B_11_init_feed size:= 1*char
char *const FIFO_Head_B_11_end_back__B_12_init_feed__0 = (char*) (Shared + 528); // FIFO_Head_B_11_end_back > B_12_init_feed size:= 1*char
char *const FIFO_Head_B_12_end_back__B_13_init_feed__0 = (char*) (Shared + 536); // FIFO_Head_B_12_end_back > B_13_init_feed size:= 1*char
char *const FIFO_Head_B_13_end_back__B_14_init_feed__0 = (char*) (Shared + 344); // FIFO_Head_B_13_end_back > B_14_init_feed size:= 1*char
char *const FIFO_Head_B_14_end_back__B_15_init_feed__0 = (char*) (Shared + 544); // FIFO_Head_B_14_end_back > B_15_init_feed size:= 1*char
char *const FIFO_Head_B_15_end_back__B_16_init_feed__0 = (char*) (Shared + 552); // FIFO_Head_B_15_end_back > B_16_init_feed size:= 1*char
uchar *const in__in__0 = (uchar*) (Shared + 0);  // frk_init_in_in > frk_0_in size:= 60*uchar
uchar *const outA__outA__0 = (uchar*) (Shared + 0);  // implode_A_end_outA_outA_outA > A_end_outA_outA size:= 60*uchar
uchar *const outA__outA_0__0 = (uchar*) (Shared + 64);  // A_0_outA > implode_A_end_outA_outA_outA_0 size:= 20*uchar
uchar *const outA__outA_1__0 = (uchar*) (Shared + 88);  // A_1_outA > implode_A_end_outA_outA_outA_1 size:= 20*uchar
uchar *const outA__outA_2__0 = (uchar*) (Shared + 112);  // A_2_outA > implode_A_end_outA_outA_outA_2 size:= 20*uchar
uchar *const out__in__0 = (uchar*) (Shared + 64);  // jn_0_out > snk_0_in size:= 17*uchar
uchar *const feed__feed__0 = (uchar*) (Shared + 136);  // B_1_init_feed_feed > B_1_0_feed size:= 1*uchar
uchar *const feed__feed__1 = (uchar*) (Shared + 144);  // B_2_init_feed_feed > B_2_0_feed size:= 1*uchar
uchar *const feed__feed__2 = (uchar*) (Shared + 152);  // B_3_init_feed_feed > B_3_0_feed size:= 1*uchar
uchar *const feed__feed__3 = (uchar*) (Shared + 160);  // B_4_init_feed_feed > B_4_0_feed size:= 1*uchar
uchar *const feed__feed__4 = (uchar*) (Shared + 168);  // B_5_init_feed_feed > B_5_0_feed size:= 1*uchar
uchar *const feed__feed__5 = (uchar*) (Shared + 176);  // B_6_init_feed_feed > B_6_0_feed size:= 1*uchar
uchar *const feed__feed__6 = (uchar*) (Shared + 184);  // B_7_init_feed_feed > B_7_0_feed size:= 1*uchar
uchar *const feed__feed__7 = (uchar*) (Shared + 192);  // B_8_init_feed_feed > B_8_0_feed size:= 1*uchar
uchar *const feed__feed__8 = (uchar*) (Shared + 200);  // B_9_init_feed_feed > B_9_0_feed size:= 1*uchar
uchar *const feed__feed__9 = (uchar*) (Shared + 208);  // B_10_init_feed_feed > B_10_0_feed size:= 1*uchar
uchar *const feed__feed__10 = (uchar*) (Shared + 216);  // B_11_init_feed_feed > B_11_0_feed size:= 1*uchar
uchar *const feed__feed__11 = (uchar*) (Shared + 224);  // B_12_init_feed_feed > B_12_0_feed size:= 1*uchar
uchar *const feed__feed__12 = (uchar*) (Shared + 232);  // B_13_init_feed_feed > B_13_0_feed size:= 1*uchar
uchar *const feed__feed__13 = (uchar*) (Shared + 240);  // B_14_init_feed_feed > B_14_0_feed size:= 1*uchar
uchar *const feed__feed__14 = (uchar*) (Shared + 248);  // B_15_init_feed_feed > B_15_0_feed size:= 1*uchar
uchar *const feed__feed__15 = (uchar*) (Shared + 256);  // B_16_init_feed_feed > B_16_0_feed size:= 1*uchar
uchar *const out__feed__0 = (uchar*) (Shared + 264);  // set_0_out > B_0_0_feed size:= 1*uchar
uchar *const newPort_00__inB__0 = (uchar*) (Shared + 272);  // frk_0_newPort_00 > B_0_0_inB size:= 1*uchar
uchar *const newPort1_01__inB__0 = (uchar*) (Shared + 280);  // frk_0_newPort1_01 > B_1_0_inB size:= 1*uchar
uchar *const newPort2_02__inB__0 = (uchar*) (Shared + 288);  // frk_0_newPort2_02 > B_2_0_inB size:= 1*uchar
uchar *const newPort3_03__inB__0 = (uchar*) (Shared + 296);  // frk_0_newPort3_03 > B_3_0_inB size:= 1*uchar
uchar *const newPort4_04__inB__0 = (uchar*) (Shared + 304);  // frk_0_newPort4_04 > B_4_0_inB size:= 1*uchar
uchar *const newPort5_05__inB__0 = (uchar*) (Shared + 312);  // frk_0_newPort5_05 > B_5_0_inB size:= 1*uchar
uchar *const newPort6_06__inB__0 = (uchar*) (Shared + 320);  // frk_0_newPort6_06 > B_6_0_inB size:= 1*uchar
uchar *const newPort7_07__inB__0 = (uchar*) (Shared + 328);  // frk_0_newPort7_07 > B_7_0_inB size:= 1*uchar
uchar *const newPort8_08__inB__0 = (uchar*) (Shared + 336);  // frk_0_newPort8_08 > B_8_0_inB size:= 1*uchar
uchar *const newPort9_09__inB__0 = (uchar*) (Shared + 344);  // frk_0_newPort9_09 > B_9_0_inB size:= 1*uchar
uchar *const newPort10_10__inB__0 = (uchar*) (Shared + 352);  // frk_0_newPort10_10 > B_10_0_inB size:= 1*uchar
uchar *const newPort11_11__inB__0 = (uchar*) (Shared + 360);  // frk_0_newPort11_11 > B_11_0_inB size:= 1*uchar
uchar *const newPort12_12__inB__0 = (uchar*) (Shared + 368);  // frk_0_newPort12_12 > B_12_0_inB size:= 1*uchar
uchar *const newPort13_13__inB__0 = (uchar*) (Shared + 376);  // frk_0_newPort13_13 > B_13_0_inB size:= 1*uchar
uchar *const newPort14_14__inB__0 = (uchar*) (Shared + 384);  // frk_0_newPort14_14 > B_14_0_inB size:= 1*uchar
uchar *const newPort15_15__inB__0 = (uchar*) (Shared + 392);  // frk_0_newPort15_15 > B_15_0_inB size:= 1*uchar
uchar *const newPort16_16__inB__0 = (uchar*) (Shared + 400);  // frk_0_newPort16_16 > B_16_0_inB size:= 1*uchar
uchar *const back__back__0 = (uchar*) (Shared + 136);  // B_5_0_back > B_5_end_back_back size:= 1*uchar
uchar *const outB__newPort5_05__0 = (uchar*) (Shared + 208);  // B_5_0_outB > jn_0_newPort5_05 size:= 1*uchar
uchar *const back__back__1 = (uchar*) (Shared + 232);  // B_1_0_back > B_1_end_back_back size:= 1*uchar
uchar *const outB__newPort1_01__0 = (uchar*) (Shared + 352);  // B_1_0_outB > jn_0_newPort1_01 size:= 1*uchar
uchar *const back__back__2 = (uchar*) (Shared + 168);  // B_9_0_back > B_9_end_back_back size:= 1*uchar
uchar *const outB__newPort9_09__0 = (uchar*) (Shared + 280);  // B_9_0_outB > jn_0_newPort9_09 size:= 1*uchar
uchar *const back__back__3 = (uchar*) (Shared + 408);  // B_10_0_back > B_10_end_back_back size:= 1*uchar
uchar *const outB__newPort10_10__0 = (uchar*) (Shared + 416);  // B_10_0_outB > jn_0_newPort10_10 size:= 1*uchar
uchar *const back__back__4 = (uchar*) (Shared + 424);  // B_13_0_back > B_13_end_back_back size:= 1*uchar
uchar *const outB__newPort13_13__0 = (uchar*) (Shared + 432);  // B_13_0_outB > jn_0_newPort13_13 size:= 1*uchar
uchar *const back__back__5 = (uchar*) (Shared + 160);  // B_0_0_back > B_0_end_back_back size:= 1*uchar
uchar *const outB__newPort0_00__0 = (uchar*) (Shared + 192);  // B_0_0_outB > jn_0_newPort0_00 size:= 1*uchar
uchar *const back__back__6 = (uchar*) (Shared + 216);  // B_2_0_back > B_2_end_back_back size:= 1*uchar
uchar *const outB__newPort2_02__0 = (uchar*) (Shared + 240);  // B_2_0_outB > jn_0_newPort2_02 size:= 1*uchar
uchar *const back__back__7 = (uchar*) (Shared + 224);  // B_3_0_back > B_3_end_back_back size:= 1*uchar
uchar *const outB__newPort3_03__0 = (uchar*) (Shared + 248);  // B_3_0_outB > jn_0_newPort3_03 size:= 1*uchar
uchar *const back__back__8 = (uchar*) (Shared + 256);  // B_4_0_back > B_4_end_back_back size:= 1*uchar
uchar *const outB__newPort4_04__0 = (uchar*) (Shared + 400);  // B_4_0_outB > jn_0_newPort4_04 size:= 1*uchar
uchar *const back__back__9 = (uchar*) (Shared + 144);  // B_6_0_back > B_6_end_back_back size:= 1*uchar
uchar *const outB__newPort6_06__0 = (uchar*) (Shared + 288);  // B_6_0_outB > jn_0_newPort6_06 size:= 1*uchar
uchar *const back__back__10 = (uchar*) (Shared + 152);  // B_7_0_back > B_7_end_back_back size:= 1*uchar
uchar *const outB__newPort7_07__0 = (uchar*) (Shared + 296);  // B_7_0_outB > jn_0_newPort7_07 size:= 1*uchar
uchar *const back__back__11 = (uchar*) (Shared + 304);  // B_8_0_back > B_8_end_back_back size:= 1*uchar
uchar *const outB__newPort8_08__0 = (uchar*) (Shared + 440);  // B_8_0_outB > jn_0_newPort8_08 size:= 1*uchar
uchar *const back__back__12 = (uchar*) (Shared + 448);  // B_11_0_back > B_11_end_back_back size:= 1*uchar
uchar *const outB__newPort11_11__0 = (uchar*) (Shared + 456);  // B_11_0_outB > jn_0_newPort11_11 size:= 1*uchar
uchar *const back__back__13 = (uchar*) (Shared + 464);  // B_12_0_back > B_12_end_back_back size:= 1*uchar
uchar *const outB__newPort12_12__0 = (uchar*) (Shared + 472);  // B_12_0_outB > jn_0_newPort12_12 size:= 1*uchar
uchar *const back__back__14 = (uchar*) (Shared + 360);  // B_14_0_back > B_14_end_back_back size:= 1*uchar
uchar *const outB__newPort14_14__0 = (uchar*) (Shared + 480);  // B_14_0_outB > jn_0_newPort14_14 size:= 1*uchar
uchar *const back__back__15 = (uchar*) (Shared + 368);  // B_15_0_back > B_15_end_back_back size:= 1*uchar
uchar *const outB__newPort15_15__0 = (uchar*) (Shared + 488);  // B_15_0_outB > jn_0_newPort15_15 size:= 1*uchar
uchar *const outB__newPort16_16__0 = (uchar*) (Shared + 496);  // B_16_0_outB > jn_0_newPort16_16 size:= 1*uchar
uchar *const back__in__0 = (uchar*) (Shared + 504);  // B_16_0_back > snk2_0_in size:= 1*uchar

void* computationThread_Core0(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_out__in__0;
	PREESM_MD5_Init(&preesm_md5_ctx_out__in__0);
#endif
  // Initialisation(s)
  fifoInit(FIFO_Head_B_0_end_back__B_1_init_feed__0, 1 * sizeof(char), NULL, 0);

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    A(outA__outA_2__0); // A_2

    sendStart(0, 2); // Core0 > Core2
    sendEnd(); // Core0 > Core2
    fifoPop(feed__feed__0, FIFO_Head_B_0_end_back__B_1_init_feed__0, 1 * sizeof(char), NULL, 0);
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    set(out__feed__0); // set_0

    receiveStart(); // Core3 > Core0
    receiveEnd(3, 0); // Core3 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    B(newPort16_16__inB__0, feed__feed__15, outB__newPort16_16__0, back__in__0); // B_16_0

    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    receiveStart(); // Core3 > Core0
    receiveEnd(3, 0); // Core3 > Core0
    B(newPort4_04__inB__0, feed__feed__3, outB__newPort4_04__0, back__back__8); // B_4_0

    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    B(newPort8_08__inB__0, feed__feed__7, outB__newPort8_08__0, back__back__11); // B_8_0

    sendStart(0, 2); // Core0 > Core2
    sendEnd(); // Core0 > Core2
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    B(newPort_00__inB__0, out__feed__0, outB__newPort0_00__0, back__back__5); // B_0_0

    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    fifoPush(back__back__5, FIFO_Head_B_0_end_back__B_1_init_feed__0, 1 * sizeof(char), NULL, 0);
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    get(out__in__0); // snk_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__in__0,(char *)out__in__0, 17);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__in__0);
	printf("preesm_md5_out__in__0 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

