/**
 * @file Core0.c
 * @generated by CPrinter
 * @date Thu Jun 01 11:28:58 CEST 2023
 *
 * Code generated for processing element Core0 (ID=0).
 */

#include "preesm_gen.h"
// Core Global Declaration
extern pthread_barrier_t iter_barrier;
extern int preesmStopThreads;

#ifdef PREESM_MD5_UPDATE
extern struct rk_sema preesmPrintSema;
#endif

// Core Global Definitions
char Shared[95]; //  size:= 95*char
char *const FIFO_Head_B_17_end_back__B_18_init_feed__0 = (char*) (Shared + 70); // FIFO_Head_B_17_end_back > B_18_init_feed size:= 1*char
char *const srcA_0__frk_0__0 = (char*) (Shared + 0);  // srcA_0 > frk_0 size:= 43*char
char *const frk_0__B_17_0__0 = (char*) (Shared + 0);  // frk_0 > B_17_0 size:= 1*char
char *const frk_0__B_18_0__0 = (char*) (Shared + 1);  // frk_0 > B_18_0 size:= 1*char
char *const frk_0__B_19_0__0 = (char*) (Shared + 2);  // frk_0 > B_19_0 size:= 1*char
char *const frk_0__B_20_0__0 = (char*) (Shared + 3);  // frk_0 > B_20_0 size:= 1*char
char *const frk_0__B_21_0__0 = (char*) (Shared + 4);  // frk_0 > B_21_0 size:= 1*char
char *const frk_0__B_22_0__0 = (char*) (Shared + 5);  // frk_0 > B_22_0 size:= 1*char
char *const frk_0__B_23_0__0 = (char*) (Shared + 6);  // frk_0 > B_23_0 size:= 1*char
char *const frk_0__B_24_0__0 = (char*) (Shared + 7);  // frk_0 > B_24_0 size:= 1*char
char *const frk_0__B_25_0__0 = (char*) (Shared + 8);  // frk_0 > B_25_0 size:= 1*char
char *const frk_0__B_26_0__0 = (char*) (Shared + 9);  // frk_0 > B_26_0 size:= 1*char
char *const frk_0__B_27_0__0 = (char*) (Shared + 10);  // frk_0 > B_27_0 size:= 1*char
char *const frk_0__B_28_0__0 = (char*) (Shared + 11);  // frk_0 > B_28_0 size:= 1*char
char *const frk_0__B_29_0__0 = (char*) (Shared + 12);  // frk_0 > B_29_0 size:= 1*char
char *const frk_0__B_30_0__0 = (char*) (Shared + 13);  // frk_0 > B_30_0 size:= 1*char
char *const frk_0__B_31_0__0 = (char*) (Shared + 14);  // frk_0 > B_31_0 size:= 1*char
char *const frk_0__B_32_0__0 = (char*) (Shared + 15);  // frk_0 > B_32_0 size:= 1*char
char *const frk_0__B_33_0__0 = (char*) (Shared + 16);  // frk_0 > B_33_0 size:= 1*char
char *const frk_0__B_34_0__0 = (char*) (Shared + 17);  // frk_0 > B_34_0 size:= 1*char
char *const frk_0__B_35_0__0 = (char*) (Shared + 18);  // frk_0 > B_35_0 size:= 1*char
char *const frk_0__B_36_0__0 = (char*) (Shared + 19);  // frk_0 > B_36_0 size:= 1*char
char *const frk_0__B_37_0__0 = (char*) (Shared + 20);  // frk_0 > B_37_0 size:= 1*char
char *const frk_0__B_38_0__0 = (char*) (Shared + 21);  // frk_0 > B_38_0 size:= 1*char
char *const frk_0__B_39_0__0 = (char*) (Shared + 22);  // frk_0 > B_39_0 size:= 1*char
char *const frk_0__snkA_0__0 = (char*) (Shared + 23);  // frk_0 > snkA_0 size:= 20*char
char *const jn_0__snkB_0__0 = (char*) (Shared + 43);  // jn_0 > snkB_0 size:= 23*char
char *const B_17_0__jn_0__0 = (char*) (Shared + 43);  // B_17_0 > jn_0 size:= 1*char
char *const B_18_0__jn_0__0 = (char*) (Shared + 44);  // B_18_0 > jn_0 size:= 1*char
char *const B_19_0__jn_0__0 = (char*) (Shared + 45);  // B_19_0 > jn_0 size:= 1*char
char *const B_20_0__jn_0__0 = (char*) (Shared + 46);  // B_20_0 > jn_0 size:= 1*char
char *const B_21_0__jn_0__0 = (char*) (Shared + 47);  // B_21_0 > jn_0 size:= 1*char
char *const B_22_0__jn_0__0 = (char*) (Shared + 48);  // B_22_0 > jn_0 size:= 1*char
char *const B_23_0__jn_0__0 = (char*) (Shared + 49);  // B_23_0 > jn_0 size:= 1*char
char *const B_24_0__jn_0__0 = (char*) (Shared + 50);  // B_24_0 > jn_0 size:= 1*char
char *const B_25_0__jn_0__0 = (char*) (Shared + 51);  // B_25_0 > jn_0 size:= 1*char
char *const B_26_0__jn_0__0 = (char*) (Shared + 52);  // B_26_0 > jn_0 size:= 1*char
char *const B_27_0__jn_0__0 = (char*) (Shared + 53);  // B_27_0 > jn_0 size:= 1*char
char *const B_28_0__jn_0__0 = (char*) (Shared + 54);  // B_28_0 > jn_0 size:= 1*char
char *const B_29_0__jn_0__0 = (char*) (Shared + 55);  // B_29_0 > jn_0 size:= 1*char
char *const B_30_0__jn_0__0 = (char*) (Shared + 56);  // B_30_0 > jn_0 size:= 1*char
char *const B_31_0__jn_0__0 = (char*) (Shared + 57);  // B_31_0 > jn_0 size:= 1*char
char *const B_32_0__jn_0__0 = (char*) (Shared + 58);  // B_32_0 > jn_0 size:= 1*char
char *const B_33_0__jn_0__0 = (char*) (Shared + 59);  // B_33_0 > jn_0 size:= 1*char
char *const B_34_0__jn_0__0 = (char*) (Shared + 60);  // B_34_0 > jn_0 size:= 1*char
char *const B_35_0__jn_0__0 = (char*) (Shared + 61);  // B_35_0 > jn_0 size:= 1*char
char *const B_36_0__jn_0__0 = (char*) (Shared + 62);  // B_36_0 > jn_0 size:= 1*char
char *const B_37_0__jn_0__0 = (char*) (Shared + 63);  // B_37_0 > jn_0 size:= 1*char
char *const B_38_0__jn_0__0 = (char*) (Shared + 64);  // B_38_0 > jn_0 size:= 1*char
char *const B_39_0__jn_0__0 = (char*) (Shared + 65);  // B_39_0 > jn_0 size:= 1*char
char *const B_18_init_feed__B_18_0__0 = (char*) (Shared + 49);  // B_18_init_feed > B_18_0 size:= 1*char
char *const B_19_init_feed__B_19_0__0 = (char*) (Shared + 50);  // B_19_init_feed > B_19_0 size:= 1*char
char *const B_20_init_feed__B_20_0__0 = (char*) (Shared + 51);  // B_20_init_feed > B_20_0 size:= 1*char
char *const B_21_init_feed__B_21_0__0 = (char*) (Shared + 53);  // B_21_init_feed > B_21_0 size:= 1*char
char *const B_22_init_feed__B_22_0__0 = (char*) (Shared + 54);  // B_22_init_feed > B_22_0 size:= 1*char
char *const B_23_init_feed__B_23_0__0 = (char*) (Shared + 55);  // B_23_init_feed > B_23_0 size:= 1*char
char *const B_24_init_feed__B_24_0__0 = (char*) (Shared + 56);  // B_24_init_feed > B_24_0 size:= 1*char
char *const B_25_init_feed__B_25_0__0 = (char*) (Shared + 57);  // B_25_init_feed > B_25_0 size:= 1*char
char *const B_26_init_feed__B_26_0__0 = (char*) (Shared + 59);  // B_26_init_feed > B_26_0 size:= 1*char
char *const B_27_init_feed__B_27_0__0 = (char*) (Shared + 58);  // B_27_init_feed > B_27_0 size:= 1*char
char *const B_28_init_feed__B_28_0__0 = (char*) (Shared + 61);  // B_28_init_feed > B_28_0 size:= 1*char
char *const B_29_init_feed__B_29_0__0 = (char*) (Shared + 62);  // B_29_init_feed > B_29_0 size:= 1*char
char *const B_30_init_feed__B_30_0__0 = (char*) (Shared + 63);  // B_30_init_feed > B_30_0 size:= 1*char
char *const B_31_init_feed__B_31_0__0 = (char*) (Shared + 66);  // B_31_init_feed > B_31_0 size:= 1*char
char *const B_32_init_feed__B_32_0__0 = (char*) (Shared + 60);  // B_32_init_feed > B_32_0 size:= 1*char
char *const B_34_init_feed__B_34_0__0 = (char*) (Shared + 67);  // B_34_init_feed > B_34_0 size:= 1*char
char *const B_35_init_feed__B_35_0__0 = (char*) (Shared + 64);  // B_35_init_feed > B_35_0 size:= 1*char
char *const B_36_init_feed__B_36_0__0 = (char*) (Shared + 68);  // B_36_init_feed > B_36_0 size:= 1*char
char *const B_37_init_feed__B_37_0__0 = (char*) (Shared + 69);  // B_37_init_feed > B_37_0 size:= 1*char
char *const B_38_init_feed__B_38_0__0 = (char*) (Shared + 65);  // B_38_init_feed > B_38_0 size:= 1*char
char *const srcD_0__B_17_0__0 = (char*) (Shared + 52);  // srcD_0 > B_17_0 size:= 1*char
char *const B_26_0__B_26_end_back__0 = (char*) (Shared + 0);  // B_26_0 > B_26_end_back size:= 1*char
char *const B_17_0__B_17_end_back__0 = (char*) (Shared + 70);  // B_17_0 > B_17_end_back size:= 1*char
char *const B_18_0__B_18_end_back__0 = (char*) (Shared + 71);  // B_18_0 > B_18_end_back size:= 1*char
char *const B_19_0__B_19_end_back__0 = (char*) (Shared + 72);  // B_19_0 > B_19_end_back size:= 1*char
char *const B_20_0__B_20_end_back__0 = (char*) (Shared + 73);  // B_20_0 > B_20_end_back size:= 1*char
char *const B_21_0__B_21_end_back__0 = (char*) (Shared + 74);  // B_21_0 > B_21_end_back size:= 1*char
char *const B_22_0__B_22_end_back__0 = (char*) (Shared + 75);  // B_22_0 > B_22_end_back size:= 1*char
char *const B_23_0__B_23_end_back__0 = (char*) (Shared + 1);  // B_23_0 > B_23_end_back size:= 1*char
char *const B_24_0__B_24_end_back__0 = (char*) (Shared + 2);  // B_24_0 > B_24_end_back size:= 1*char
char *const B_25_0__B_25_end_back__0 = (char*) (Shared + 3);  // B_25_0 > B_25_end_back size:= 1*char
char *const B_27_0__B_27_end_back__0 = (char*) (Shared + 4);  // B_27_0 > B_27_end_back size:= 1*char
char *const B_28_0__B_28_end_back__0 = (char*) (Shared + 5);  // B_28_0 > B_28_end_back size:= 1*char
char *const B_29_0__B_29_end_back__0 = (char*) (Shared + 6);  // B_29_0 > B_29_end_back size:= 1*char
char *const B_30_0__B_30_end_back__0 = (char*) (Shared + 7);  // B_30_0 > B_30_end_back size:= 1*char
char *const B_31_0__B_31_end_back__0 = (char*) (Shared + 8);  // B_31_0 > B_31_end_back size:= 1*char
char *const B_32_0__B_33_0__0 = (char*) (Shared + 10);  // B_32_0 > B_33_0 size:= 1*char
char *const B_34_0__B_34_end_back__0 = (char*) (Shared + 15);  // B_34_0 > B_34_end_back size:= 1*char
char *const B_35_0__B_35_end_back__0 = (char*) (Shared + 11);  // B_35_0 > B_35_end_back size:= 1*char
char *const B_36_0__B_36_end_back__0 = (char*) (Shared + 12);  // B_36_0 > B_36_end_back size:= 1*char
char *const B_37_0__B_37_end_back__0 = (char*) (Shared + 13);  // B_37_0 > B_37_end_back size:= 1*char
char *const B_38_0__B_39_0__0 = (char*) (Shared + 18);  // B_38_0 > B_39_0 size:= 1*char
char *const B_33_0__B_33_end_back__0 = (char*) (Shared + 9);  // B_33_0 > B_33_end_back size:= 1*char
char *const B_39_0__snkD_0__0 = (char*) (Shared + 10);  // B_39_0 > snkD_0 size:= 1*char
char *const FIFO_Head_B_18_end_back__B_19_init_feed__0 = (char*) (Shared + 76); // FIFO_Head_B_18_end_back > B_19_init_feed size:= 1*char
char *const FIFO_Head_B_19_end_back__B_20_init_feed__0 = (char*) (Shared + 77); // FIFO_Head_B_19_end_back > B_20_init_feed size:= 1*char
char *const FIFO_Head_B_20_end_back__B_21_init_feed__0 = (char*) (Shared + 78); // FIFO_Head_B_20_end_back > B_21_init_feed size:= 1*char
char *const FIFO_Head_B_21_end_back__B_22_init_feed__0 = (char*) (Shared + 79); // FIFO_Head_B_21_end_back > B_22_init_feed size:= 1*char
char *const FIFO_Head_B_22_end_back__B_23_init_feed__0 = (char*) (Shared + 80); // FIFO_Head_B_22_end_back > B_23_init_feed size:= 1*char
char *const FIFO_Head_B_23_end_back__B_24_init_feed__0 = (char*) (Shared + 81); // FIFO_Head_B_23_end_back > B_24_init_feed size:= 1*char
char *const FIFO_Head_B_24_end_back__B_25_init_feed__0 = (char*) (Shared + 82); // FIFO_Head_B_24_end_back > B_25_init_feed size:= 1*char
char *const FIFO_Head_B_25_end_back__B_26_init_feed__0 = (char*) (Shared + 83); // FIFO_Head_B_25_end_back > B_26_init_feed size:= 1*char
char *const FIFO_Head_B_26_end_back__B_27_init_feed__0 = (char*) (Shared + 84); // FIFO_Head_B_26_end_back > B_27_init_feed size:= 1*char
char *const FIFO_Head_B_27_end_back__B_28_init_feed__0 = (char*) (Shared + 85); // FIFO_Head_B_27_end_back > B_28_init_feed size:= 1*char
char *const FIFO_Head_B_28_end_back__B_29_init_feed__0 = (char*) (Shared + 86); // FIFO_Head_B_28_end_back > B_29_init_feed size:= 1*char
char *const FIFO_Head_B_29_end_back__B_30_init_feed__0 = (char*) (Shared + 87); // FIFO_Head_B_29_end_back > B_30_init_feed size:= 1*char
char *const FIFO_Head_B_30_end_back__B_31_init_feed__0 = (char*) (Shared + 88); // FIFO_Head_B_30_end_back > B_31_init_feed size:= 1*char
char *const FIFO_Head_B_31_end_back__B_32_init_feed__0 = (char*) (Shared + 89); // FIFO_Head_B_31_end_back > B_32_init_feed size:= 1*char
char *const FIFO_Head_B_33_end_back__B_34_init_feed__0 = (char*) (Shared + 90); // FIFO_Head_B_33_end_back > B_34_init_feed size:= 1*char
char *const FIFO_Head_B_34_end_back__B_35_init_feed__0 = (char*) (Shared + 91); // FIFO_Head_B_34_end_back > B_35_init_feed size:= 1*char
char *const FIFO_Head_B_35_end_back__B_36_init_feed__0 = (char*) (Shared + 92); // FIFO_Head_B_35_end_back > B_36_init_feed size:= 1*char
char *const FIFO_Head_B_36_end_back__B_37_init_feed__0 = (char*) (Shared + 93); // FIFO_Head_B_36_end_back > B_37_init_feed size:= 1*char
char *const FIFO_Head_B_37_end_back__B_38_init_feed__0 = (char*) (Shared + 94); // FIFO_Head_B_37_end_back > B_38_init_feed size:= 1*char
uchar *const out__in__0 = (uchar*) (Shared + 0);  // srcA_0_out > frk_0_in size:= 43*uchar
uchar *const newPort_00__inB__0 = (uchar*) (Shared + 0);  // frk_0_newPort_00 > B_17_0_inB size:= 1*uchar
uchar *const newPort1_01__inB__0 = (uchar*) (Shared + 1);  // frk_0_newPort1_01 > B_18_0_inB size:= 1*uchar
uchar *const newPort2_02__inB__0 = (uchar*) (Shared + 2);  // frk_0_newPort2_02 > B_19_0_inB size:= 1*uchar
uchar *const newPort3_03__inB__0 = (uchar*) (Shared + 3);  // frk_0_newPort3_03 > B_20_0_inB size:= 1*uchar
uchar *const newPort4_04__inB__0 = (uchar*) (Shared + 4);  // frk_0_newPort4_04 > B_21_0_inB size:= 1*uchar
uchar *const newPort5_05__inB__0 = (uchar*) (Shared + 5);  // frk_0_newPort5_05 > B_22_0_inB size:= 1*uchar
uchar *const newPort6_06__inB__0 = (uchar*) (Shared + 6);  // frk_0_newPort6_06 > B_23_0_inB size:= 1*uchar
uchar *const newPort7_07__inB__0 = (uchar*) (Shared + 7);  // frk_0_newPort7_07 > B_24_0_inB size:= 1*uchar
uchar *const newPort8_08__inB__0 = (uchar*) (Shared + 8);  // frk_0_newPort8_08 > B_25_0_inB size:= 1*uchar
uchar *const newPort9_09__inB__0 = (uchar*) (Shared + 9);  // frk_0_newPort9_09 > B_26_0_inB size:= 1*uchar
uchar *const newPort10_10__inB__0 = (uchar*) (Shared + 10);  // frk_0_newPort10_10 > B_27_0_inB size:= 1*uchar
uchar *const newPort11_11__inB__0 = (uchar*) (Shared + 11);  // frk_0_newPort11_11 > B_28_0_inB size:= 1*uchar
uchar *const newPort12_12__inB__0 = (uchar*) (Shared + 12);  // frk_0_newPort12_12 > B_29_0_inB size:= 1*uchar
uchar *const newPort13_13__inB__0 = (uchar*) (Shared + 13);  // frk_0_newPort13_13 > B_30_0_inB size:= 1*uchar
uchar *const newPort14_14__inB__0 = (uchar*) (Shared + 14);  // frk_0_newPort14_14 > B_31_0_inB size:= 1*uchar
uchar *const newPort15_15__inB__0 = (uchar*) (Shared + 15);  // frk_0_newPort15_15 > B_32_0_inB size:= 1*uchar
uchar *const newPort16_16__inB__0 = (uchar*) (Shared + 16);  // frk_0_newPort16_16 > B_33_0_inB size:= 1*uchar
uchar *const newPort17_17__inB__0 = (uchar*) (Shared + 17);  // frk_0_newPort17_17 > B_34_0_inB size:= 1*uchar
uchar *const newPort18_18__inB__0 = (uchar*) (Shared + 18);  // frk_0_newPort18_18 > B_35_0_inB size:= 1*uchar
uchar *const newPort19_19__inB__0 = (uchar*) (Shared + 19);  // frk_0_newPort19_19 > B_36_0_inB size:= 1*uchar
uchar *const newPort20_20__inB__0 = (uchar*) (Shared + 20);  // frk_0_newPort20_20 > B_37_0_inB size:= 1*uchar
uchar *const newPort21_21__inB__0 = (uchar*) (Shared + 21);  // frk_0_newPort21_21 > B_38_0_inB size:= 1*uchar
uchar *const newPort22_22__inB__0 = (uchar*) (Shared + 22);  // frk_0_newPort22_22 > B_39_0_inB size:= 1*uchar
uchar *const newPort35_23__in__0 = (uchar*) (Shared + 23);  // frk_0_newPort35_23 > snkA_0_in size:= 20*uchar
uchar *const out__in__1 = (uchar*) (Shared + 43);  // jn_0_out > snkB_0_in size:= 23*uchar
uchar *const outB__newPort0_00__0 = (uchar*) (Shared + 43);  // B_17_0_outB > jn_0_newPort0_00 size:= 1*uchar
uchar *const outB__newPort1_01__0 = (uchar*) (Shared + 44);  // B_18_0_outB > jn_0_newPort1_01 size:= 1*uchar
uchar *const outB__newPort2_02__0 = (uchar*) (Shared + 45);  // B_19_0_outB > jn_0_newPort2_02 size:= 1*uchar
uchar *const outB__newPort3_03__0 = (uchar*) (Shared + 46);  // B_20_0_outB > jn_0_newPort3_03 size:= 1*uchar
uchar *const outB__newPort4_04__0 = (uchar*) (Shared + 47);  // B_21_0_outB > jn_0_newPort4_04 size:= 1*uchar
uchar *const outB__newPort5_05__0 = (uchar*) (Shared + 48);  // B_22_0_outB > jn_0_newPort5_05 size:= 1*uchar
uchar *const outB__newPort6_06__0 = (uchar*) (Shared + 49);  // B_23_0_outB > jn_0_newPort6_06 size:= 1*uchar
uchar *const outB__newPort7_07__0 = (uchar*) (Shared + 50);  // B_24_0_outB > jn_0_newPort7_07 size:= 1*uchar
uchar *const outB__newPort8_08__0 = (uchar*) (Shared + 51);  // B_25_0_outB > jn_0_newPort8_08 size:= 1*uchar
uchar *const outB__newPort9_09__0 = (uchar*) (Shared + 52);  // B_26_0_outB > jn_0_newPort9_09 size:= 1*uchar
uchar *const outB__newPort10_10__0 = (uchar*) (Shared + 53);  // B_27_0_outB > jn_0_newPort10_10 size:= 1*uchar
uchar *const outB__newPort11_11__0 = (uchar*) (Shared + 54);  // B_28_0_outB > jn_0_newPort11_11 size:= 1*uchar
uchar *const outB__newPort12_12__0 = (uchar*) (Shared + 55);  // B_29_0_outB > jn_0_newPort12_12 size:= 1*uchar
uchar *const outB__newPort13_13__0 = (uchar*) (Shared + 56);  // B_30_0_outB > jn_0_newPort13_13 size:= 1*uchar
uchar *const outB__newPort14_14__0 = (uchar*) (Shared + 57);  // B_31_0_outB > jn_0_newPort14_14 size:= 1*uchar
uchar *const outB__newPort15_15__0 = (uchar*) (Shared + 58);  // B_32_0_outB > jn_0_newPort15_15 size:= 1*uchar
uchar *const outB__newPort16_16__0 = (uchar*) (Shared + 59);  // B_33_0_outB > jn_0_newPort16_16 size:= 1*uchar
uchar *const outB__newPort17_17__0 = (uchar*) (Shared + 60);  // B_34_0_outB > jn_0_newPort17_17 size:= 1*uchar
uchar *const outB__newPort18_18__0 = (uchar*) (Shared + 61);  // B_35_0_outB > jn_0_newPort18_18 size:= 1*uchar
uchar *const outB__newPort19_19__0 = (uchar*) (Shared + 62);  // B_36_0_outB > jn_0_newPort19_19 size:= 1*uchar
uchar *const outB__newPort20_20__0 = (uchar*) (Shared + 63);  // B_37_0_outB > jn_0_newPort20_20 size:= 1*uchar
uchar *const outB__newPort21_21__0 = (uchar*) (Shared + 64);  // B_38_0_outB > jn_0_newPort21_21 size:= 1*uchar
uchar *const outB__newPort22_22__0 = (uchar*) (Shared + 65);  // B_39_0_outB > jn_0_newPort22_22 size:= 1*uchar
uchar *const feed__feed__0 = (uchar*) (Shared + 49);  // B_18_init_feed_feed > B_18_0_feed size:= 1*uchar
uchar *const feed__feed__1 = (uchar*) (Shared + 50);  // B_19_init_feed_feed > B_19_0_feed size:= 1*uchar
uchar *const feed__feed__2 = (uchar*) (Shared + 51);  // B_20_init_feed_feed > B_20_0_feed size:= 1*uchar
uchar *const feed__feed__3 = (uchar*) (Shared + 53);  // B_21_init_feed_feed > B_21_0_feed size:= 1*uchar
uchar *const feed__feed__4 = (uchar*) (Shared + 54);  // B_22_init_feed_feed > B_22_0_feed size:= 1*uchar
uchar *const feed__feed__5 = (uchar*) (Shared + 55);  // B_23_init_feed_feed > B_23_0_feed size:= 1*uchar
uchar *const feed__feed__6 = (uchar*) (Shared + 56);  // B_24_init_feed_feed > B_24_0_feed size:= 1*uchar
uchar *const feed__feed__7 = (uchar*) (Shared + 57);  // B_25_init_feed_feed > B_25_0_feed size:= 1*uchar
uchar *const feed__feed__8 = (uchar*) (Shared + 59);  // B_26_init_feed_feed > B_26_0_feed size:= 1*uchar
uchar *const feed__feed__9 = (uchar*) (Shared + 58);  // B_27_init_feed_feed > B_27_0_feed size:= 1*uchar
uchar *const feed__feed__10 = (uchar*) (Shared + 61);  // B_28_init_feed_feed > B_28_0_feed size:= 1*uchar
uchar *const feed__feed__11 = (uchar*) (Shared + 62);  // B_29_init_feed_feed > B_29_0_feed size:= 1*uchar
uchar *const feed__feed__12 = (uchar*) (Shared + 63);  // B_30_init_feed_feed > B_30_0_feed size:= 1*uchar
uchar *const feed__feed__13 = (uchar*) (Shared + 66);  // B_31_init_feed_feed > B_31_0_feed size:= 1*uchar
uchar *const feed__feed__14 = (uchar*) (Shared + 60);  // B_32_init_feed_feed > B_32_0_feed size:= 1*uchar
uchar *const feed__feed__15 = (uchar*) (Shared + 67);  // B_34_init_feed_feed > B_34_0_feed size:= 1*uchar
uchar *const feed__feed__16 = (uchar*) (Shared + 64);  // B_35_init_feed_feed > B_35_0_feed size:= 1*uchar
uchar *const feed__feed__17 = (uchar*) (Shared + 68);  // B_36_init_feed_feed > B_36_0_feed size:= 1*uchar
uchar *const feed__feed__18 = (uchar*) (Shared + 69);  // B_37_init_feed_feed > B_37_0_feed size:= 1*uchar
uchar *const feed__feed__19 = (uchar*) (Shared + 65);  // B_38_init_feed_feed > B_38_0_feed size:= 1*uchar
uchar *const out__feed__0 = (uchar*) (Shared + 52);  // srcD_0_out > B_17_0_feed size:= 1*uchar
uchar *const back__back__0 = (uchar*) (Shared + 0);  // B_26_0_back > B_26_end_back_back size:= 1*uchar
uchar *const back__back__1 = (uchar*) (Shared + 70);  // B_17_0_back > B_17_end_back_back size:= 1*uchar
uchar *const back__back__2 = (uchar*) (Shared + 71);  // B_18_0_back > B_18_end_back_back size:= 1*uchar
uchar *const back__back__3 = (uchar*) (Shared + 72);  // B_19_0_back > B_19_end_back_back size:= 1*uchar
uchar *const back__back__4 = (uchar*) (Shared + 73);  // B_20_0_back > B_20_end_back_back size:= 1*uchar
uchar *const back__back__5 = (uchar*) (Shared + 74);  // B_21_0_back > B_21_end_back_back size:= 1*uchar
uchar *const back__back__6 = (uchar*) (Shared + 75);  // B_22_0_back > B_22_end_back_back size:= 1*uchar
uchar *const back__back__7 = (uchar*) (Shared + 1);  // B_23_0_back > B_23_end_back_back size:= 1*uchar
uchar *const back__back__8 = (uchar*) (Shared + 2);  // B_24_0_back > B_24_end_back_back size:= 1*uchar
uchar *const back__back__9 = (uchar*) (Shared + 3);  // B_25_0_back > B_25_end_back_back size:= 1*uchar
uchar *const back__back__10 = (uchar*) (Shared + 4);  // B_27_0_back > B_27_end_back_back size:= 1*uchar
uchar *const back__back__11 = (uchar*) (Shared + 5);  // B_28_0_back > B_28_end_back_back size:= 1*uchar
uchar *const back__back__12 = (uchar*) (Shared + 6);  // B_29_0_back > B_29_end_back_back size:= 1*uchar
uchar *const back__back__13 = (uchar*) (Shared + 7);  // B_30_0_back > B_30_end_back_back size:= 1*uchar
uchar *const back__back__14 = (uchar*) (Shared + 8);  // B_31_0_back > B_31_end_back_back size:= 1*uchar
uchar *const back__feed__0 = (uchar*) (Shared + 10);  // B_32_0_back > B_33_0_feed size:= 1*uchar
uchar *const back__back__15 = (uchar*) (Shared + 15);  // B_34_0_back > B_34_end_back_back size:= 1*uchar
uchar *const back__back__16 = (uchar*) (Shared + 11);  // B_35_0_back > B_35_end_back_back size:= 1*uchar
uchar *const back__back__17 = (uchar*) (Shared + 12);  // B_36_0_back > B_36_end_back_back size:= 1*uchar
uchar *const back__back__18 = (uchar*) (Shared + 13);  // B_37_0_back > B_37_end_back_back size:= 1*uchar
uchar *const back__feed__1 = (uchar*) (Shared + 18);  // B_38_0_back > B_39_0_feed size:= 1*uchar
uchar *const back__back__19 = (uchar*) (Shared + 9);  // B_33_0_back > B_33_end_back_back size:= 1*uchar
uchar *const back__in__0 = (uchar*) (Shared + 10);  // B_39_0_back > snkD_0_in size:= 1*uchar

void* computationThread_Core0(void *arg) {
  if (arg != NULL) {
    printf("Warning: expecting NULL arguments\n");
    fflush (stdout);
  }

#ifdef PREESM_MD5_UPDATE
	PREESM_MD5_CTX preesm_md5_ctx_out__in__1;
	PREESM_MD5_Init(&preesm_md5_ctx_out__in__1);
#endif
  // Initialisation(s)

  fifoInit(FIFO_Head_B_17_end_back__B_18_init_feed__0, 1, NULL, 0); // 1 * char

  // Begin the execution loop
  pthread_barrier_wait(&iter_barrier);
#ifdef PREESM_LOOP_SIZE // Case of a finite loop
	int index;
	for(index=0;index<PREESM_LOOP_SIZE && !preesmStopThreads;index++){
#else // Default case of an infinite loop
  while (!preesmStopThreads) {
#endif
    // loop body
    fifoPop(feed__feed__0, FIFO_Head_B_17_end_back__B_18_init_feed__0, 1, NULL, 0); // 1 * char
    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    src(out__in__0); // srcA_0

    // Fork frk_0

    {
    }
    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    sendStart(0, 4); // Core0 > Core4
    sendEnd(); // Core0 > Core4
    sendStart(0, 5); // Core0 > Core5
    sendEnd(); // Core0 > Core5
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    sendStart(0, 2); // Core0 > Core2
    sendEnd(); // Core0 > Core2
    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    sendStart(0, 4); // Core0 > Core4
    sendEnd(); // Core0 > Core4
    sendStart(0, 5); // Core0 > Core5
    sendEnd(); // Core0 > Core5
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    sendStart(0, 2); // Core0 > Core2
    sendEnd(); // Core0 > Core2
    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    sendStart(0, 4); // Core0 > Core4
    sendEnd(); // Core0 > Core4
    sendStart(0, 5); // Core0 > Core5
    sendEnd(); // Core0 > Core5
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    sendStart(0, 2); // Core0 > Core2
    sendEnd(); // Core0 > Core2
    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    sendStart(0, 4); // Core0 > Core4
    sendEnd(); // Core0 > Core4
    sendStart(0, 2); // Core0 > Core2
    sendEnd(); // Core0 > Core2
    sendStart(0, 5); // Core0 > Core5
    sendEnd(); // Core0 > Core5
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    B(newPort_00__inB__0, out__feed__0, outB__newPort0_00__0, back__back__1); // B_17_0

    receiveStart(); // Core5 > Core0
    receiveEnd(5, 0); // Core5 > Core0
    B(newPort9_09__inB__0, feed__feed__8, outB__newPort9_09__0, back__back__0); // B_26_0

    sendStart(0, 3); // Core0 > Core3
    sendEnd(); // Core0 > Core3
    fifoPush(back__back__1, FIFO_Head_B_17_end_back__B_18_init_feed__0, 1, NULL, 0); // 1 * char
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    B(newPort16_16__inB__0, back__feed__0, outB__newPort16_16__0, back__back__19); // B_33_0

    sendStart(0, 5); // Core0 > Core5
    sendEnd(); // Core0 > Core5
    receiveStart(); // Core2 > Core0
    receiveEnd(2, 0); // Core2 > Core0
    receiveStart(); // Core2 > Core0
    receiveEnd(2, 0); // Core2 > Core0
    receiveStart(); // Core2 > Core0
    receiveEnd(2, 0); // Core2 > Core0
    receiveStart(); // Core2 > Core0
    receiveEnd(2, 0); // Core2 > Core0
    B(newPort22_22__inB__0, back__feed__1, outB__newPort22_22__0, back__in__0); // B_39_0

    sendStart(0, 1); // Core0 > Core1
    sendEnd(); // Core0 > Core1
    receiveStart(); // Core3 > Core0
    receiveEnd(3, 0); // Core3 > Core0
    receiveStart(); // Core4 > Core0
    receiveEnd(4, 0); // Core4 > Core0
    receiveStart(); // Core5 > Core0
    receiveEnd(5, 0); // Core5 > Core0
    receiveStart(); // Core3 > Core0
    receiveEnd(3, 0); // Core3 > Core0
    receiveStart(); // Core4 > Core0
    receiveEnd(4, 0); // Core4 > Core0
    receiveStart(); // Core5 > Core0
    receiveEnd(5, 0); // Core5 > Core0
    receiveStart(); // Core3 > Core0
    receiveEnd(3, 0); // Core3 > Core0
    receiveStart(); // Core4 > Core0
    receiveEnd(4, 0); // Core4 > Core0
    receiveStart(); // Core5 > Core0
    receiveEnd(5, 0); // Core5 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core1 > Core0
    receiveEnd(1, 0); // Core1 > Core0
    receiveStart(); // Core3 > Core0
    receiveEnd(3, 0); // Core3 > Core0
    receiveStart(); // Core4 > Core0
    receiveEnd(4, 0); // Core4 > Core0
    receiveStart(); // Core2 > Core0
    receiveEnd(2, 0); // Core2 > Core0
    // Join jn_0

    {
    }
    snk(out__in__1); // snkB_0
#ifdef PREESM_MD5_UPDATE
		PREESM_MD5_Update(&preesm_md5_ctx_out__in__1,(char *)out__in__1, 23);
		#endif

    // loop footer
    pthread_barrier_wait(&iter_barrier);

  }

#ifdef PREESM_MD5_UPDATE
	// Print MD5
	rk_sema_wait(&preesmPrintSema);
	unsigned char preesm_md5_chars_final[20] = { 0 };
	PREESM_MD5_Final(preesm_md5_chars_final, &preesm_md5_ctx_out__in__1);
	printf("preesm_md5_out__in__1 : ");
	for (int i = 16; i > 0; i -= 1){
		printf("%02x", *(preesm_md5_chars_final + i - 1));
	}
	printf("\n");
	fflush(stdout);
	rk_sema_post(&preesmPrintSema);
#endif

  return NULL;
}

